POST http://localhost:3333
Content-Type: application/json

{
    "coffee": "Bebida: espresso",
    "milk": "Sem leite",
    "additionals": "Sem adicional",
    "name": "Amanda"
}

###

GET http://localhost:3333

###

PATCH http://localhost:3333
Content-Type: application/json

{
    "id": 2
}